Allow files in same directory to be loaded without prefixing './'
s-zeng/dhall-python pull request #86
Opened 2022-08-24 16:13 UTC by ndwarshuis

2022-08-24 23:23 UTC, s-zeng requested changes
Thanks for contributing! Let's get the test passing again, and maybe add a test as well, and we should be good to go

2022-08-24 23:23 UTC, s-zeng commented on dhall/__init__.py
> +            os.chdir()
Looks like you just need to put in the newdir argument and you should be good.

2022-08-25 20:29 UTC, ndwarshuis commented
Fixed typo and also added a new test (and the tests should actually pass). I just reused the already-present test file for the new test and called it in a slightly different order; hopefully that's clear enough.

2022-09-02 14:41 UTC, ndwarshuis commented
@s-zeng were you still waiting on me to do something more with this?

2022-09-03 02:54 UTC, s-zeng approved these changes

2022-09-03 02:54 UTC, merged

2022-09-03 13:51 UTC, ndwarshuis commented
thanks :)